export const OZU = [
    { value: "1", label: "1" },
    { value: "1.5", label: "1.5" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
    { value: "6", label: "6" },
    { value: "8", label: "8" },
    { value: "12", label: "12" },
    { value: "16", label: "16" },
    { value: "18", label: "18" },
    { value: "20", label: "20" },
    { value: "24", label: "24" },
    { value: "32", label: "32" },
    { value: "40", label: "40" },
    { value: "48", label: "48" },
    { value: "64", label: "64" },
    { value: "96", label: "96" },
    { value: "128", label: "128" },
    { value: "Отсутствует", label: "Отсутствует" }
  ];